version: '3.8'

services:
  # Servicio de Base de Datos
  postgres_db:
    image: postgres:15-alpine
    container_name: sales_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sales_inventory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Servicio de la Aplicación NestJS
  api:
    build: .
    container_name: sales_api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      # <--- Añade esto
      - .env # <--- Docker leerá el archivo .env
    depends_on:
      - postgres_db

volumes:
  pgdata:
